### ISSUE TITLE
Make a simple Registration page 

### ISSUE THREAD

**Issue by Ares358** [Ares358/Basic-Registration-Website#1]
Using HTML and CSS, make a simple registration page that asks the user for :

- First Name
- Last Name
- Email Address
- Password
- Confirm Password
- Terms and Conditions checkbox

The output could look something like this, but is not restricted to be like this 
![image](https://user-images.githubusercontent.com/52101053/97577037-e34bdd00-1a14-11eb-80b8-b2ebebc01978.png)

**Comment by spartaabhishek** [comment]
Assign me this

**Comment by Anurag-ak99** [comment]
can I contribute in this issue? Is it still open then please assign it to me.

**Comment by Ares358** [comment]
> 
> 
> can I contribute in this issue? Is it still open then please assign it to me.

I was just gonna close this issue as I just merged a PR solving this.
But sure, I'll assign this to you and you can give this a try as well!
Read the [signup.html](https://github.com/Ares358/Basic-Registration-Website/blob/main/signup.html) file and see if you can do it better!

**Comment by Anurag-ak99** [comment]
okay , Thanks
