### ISSUE TITLE
Make a simple MySQL Database and store user registration details into it using PHP

### ISSUE THREAD

**Issue by Ares358** [Ares358/Basic-Registration-Website#3]
What the title says. 
You'll need to create a MySQL database and use PHP to connect and add data(Username, Email and Password. Possibly Time of registration as well) from the signup form into the database.

The following links might be useful if you are not very familiar with the above but still wanna give it a try- 

https://www.w3schools.com/php/php_mysql_connect.asp
https://www.w3schools.com/php/php_mysql_create.asp
https://www.w3schools.com/php/php_mysql_create_table.asp
https://www.w3schools.com/php/php_mysql_insert.asp

**Comment by spartaabhishek** [comment]
assign me @Ares358
