### ISSUE TITLE
Add simple data validation to form using JS

### ISSUE THREAD

**Issue by Ares358** [Ares358/Basic-Registration-Website#4]
Add some basic validation functions using JavaScript in [signup.html](https://github.com/Ares358/Basic-Registration-Website/blob/main/signup.html) and allow submissions only when everything has been validated.

Validations to consider : 
- Make sure the provided Email ID is valid
- Make sure password length > 8 and contains at least one lowercase, one uppercase and one special character.
- Make sure both the passwords are the same
- Make sure the checkbox has been ticked

**Comment by Anurag-ak99** [comment]
Can I will add these validations in the form

**Comment by spartaabhishek** [comment]
i wanna try this @Ares358
